/**
 * This file is automatically generated by the Firebase setup steps.
 */
import { FirebaseOptions } from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  projectId: "studio-4324599374-5cd58",
  appId: "1:362806825748:web:44b117e5a108076543a801",
  apiKey: "AIzaSyCJfYSlB5lwMya9DMXxUd4DJ3IjatymwrQ",
  authDomain: "studio-4324599374-5cd58.firebaseapp.com",
  measurementId: "",
  messagingSenderId: "362806825748",
};
