-- Migration tracking table
-- Keeps track of which migrations have been applied so scripts can safely skip duplicates.

CREATE TABLE IF NOT EXISTS public.schema_migrations (
  id SERIAL PRIMARY KEY,
  filename TEXT NOT NULL UNIQUE,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Seed all existing migrations so they won't be re-run
INSERT INTO public.schema_migrations (filename) VALUES
  ('001_add_user_id.sql'),
  ('001_add_user_id_safe.sql'),
  ('002_create_profiles.sql'),
  ('003_create_smart_input_feedback.sql'),
  ('004_fix_v_sprayable_parcels_left_join.sql'),
  ('005_storage_tables.sql'),
  ('006_storage_complex_redesign.sql'),
  ('007_storage_status_and_variety_counts.sql'),
  ('008_sub_parcel_storage.sql'),
  ('009_harvest_registrations.sql'),
  ('010_weather_tables.sql'),
  ('011_knowledge_base_tables.sql'),
  ('012_fertilizer_registration_support.sql'),
  ('013_fix_auth_and_rls.sql'),
  ('014_knmi_observations.sql'),
  ('015_parcel_groups_and_synonyms.sql'),
  ('016_brp_crop_history.sql'),
  ('017_brp_nationaal.sql'),
  ('018_fruitteelt_meststoffen.sql'),
  ('019_fertilizer_enrichment.sql'),
  ('020_fertilizer_enrichment_remaining.sql'),
  ('021_fertilizer_enrichment_batch3.sql'),
  ('022_composition_forms.sql'),
  ('023_analytics_harvest_year.sql'),
  ('024_production_summaries.sql'),
  ('025_field_notes.sql'),
  ('026_whatsapp_tables.sql'),
  ('027_field_notes_v2.sql'),
  ('028_field_notes_multi_parcel.sql'),
  ('029_whatsapp_fix.sql'),
  ('029_field_notes_observation.sql'),
  ('030_field_notes_photo_gps.sql'),
  ('031_field_notes_lock.sql'),
  ('032_spuitschrift_hidden_products.sql'),
  ('033_unified_products.sql'),
  ('034_ctgb_enhancements.sql'),
  ('034_field_notes_tasks.sql'),
  ('035_fertilizer_dedup.sql'),
  ('036_unified_aliases.sql'),
  ('037_whatsapp_product_views.sql'),
  ('038_sync_infrastructure.sql'),
  ('039_enrich_active_substances.sql'),
  ('039_fix_parcel_history_columns.sql'),
  ('040_parcel_profiles_and_soil_analyses.sql'),
  ('040_enrich_active_substances_v2.sql'),
  ('041_cascade_to_set_null.sql'),
  ('041_fix_restrictions_index.sql'),
  ('042_onderstammen_jsonb.sql'),
  ('042_gv_01.sql'),
  ('042_gv_02.sql'),
  ('042_gv_03.sql'),
  ('042_gv_04.sql'),
  ('042_gv_05.sql'),
  ('042_gv_06.sql'),
  ('042_gv_07.sql'),
  ('042_gv_08.sql'),
  ('042_gv_09.sql'),
  ('042_gv_10.sql'),
  ('042_gv_11.sql'),
  ('042_gv_12.sql'),
  ('042_gv_13.sql'),
  ('042_gv_14.sql'),
  ('042_gv_15.sql'),
  ('042_gv_16.sql'),
  ('042_gv_17.sql'),
  ('042_gv_18.sql'),
  ('042_gv_19.sql'),
  ('042_gv_20.sql'),
  ('042_gv_21.sql'),
  ('043_disease_pressure.sql'),
  ('044_fix_rls_public_read.sql'),
  ('045_create_knowledge_articles.sql'),
  ('045_fix_whatsapp_gv_filter.sql'),
  ('046_phenology_reference.sql'),
  ('047_chat_history.sql'),
  ('048_fix_vector_index.sql'),
  ('049_structured_knowledge_tables.sql'),
  ('050_add_image_urls_column.sql'),
  ('051_schema_migrations_tracking.sql')
ON CONFLICT (filename) DO NOTHING;
